### ISSUE TITLE
Training error!

### ISSUE THREAD

**Issue by Falmi** [tuanchien/asd#4]
I generated the image, video, and mfcc file according to the procedure you provide, thanks. But the code generates the following error during training. Could you help,please.
![image](https://user-images.githubusercontent.com/26068376/104535278-db352e00-5650-11eb-8228-005ceb86cf98.png)

**Comment by tuanchien** [comment]
Did you also provide the annotations?

You might want to have a read through https://github.com/tuanchien/asd/issues/2 as it seems like you are trying to accomplish something similar.

**Comment by Falmi** [comment]
I generated only training and test annotation pkl files. Are those files expected to be generated before training?
![image](https://user-images.githubusercontent.com/26068376/104540988-9a8ee200-565b-11eb-9249-fa5079422646.png)

**Comment by Falmi** [comment]
Solved, Thanks!
