### ISSUE TITLE
Error while extracting mfcc features

### ISSUE THREAD

**Issue by godatta** [tuanchien/asd#7]
The audio.wav file is being stored inside each folder extracting the videos.

<img width="1115" alt="Screen Shot 2021-06-03 at 6 45 02 PM" src="https://user-images.githubusercontent.com/46044371/120733339-cfc98e80-c49b-11eb-9f69-44a16e7d5ca5.png">

**Comment by tuanchien** [comment]
Can you paste the code, commands, and configuration you are trying to run and use?

The output looks very odd. For example, it is thinking the pickle file 'test_annotations.pkl' is the name of a directory.

**Comment by godatta** [comment]
Thanks, I fixed this error. It was due to some directory mismatch in the config file.

However, I am running into this error (please see attached), whenever I try to evaluate your model (execute the evaluate.py file). Can you please let me know your CudaDNN and coda version since I suspect it might be a version issue. Or do you have any suggestions as to how can I fix this error?

Configuration of my machine is 

NVIDIA-SMI 450.119.03   Driver Version: 450.119.03   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P0    24W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               

<img width="1194" alt="Screen Shot 2021-06-05 at 2 59 55 AM" src="https://user-images.githubusercontent.com/46044371/120887861-1d342180-c5aa-11eb-9610-fcc2f0d150ae.png">

**Comment by tuanchien** [comment]
cuda 10.2 worked for me.
