### ISSUE TITLE
Agumenetation

### ISSUE THREAD

**Issue by Falmi** [tuanchien/asd#8]
I  can see that you left the augmentation functions empty. I was wondering if you would have code for both mfcc and video data augmentation, and I would also appreciate it if you recommended a resource to do that if you don't have the code.
Best,

**Comment by godatta** [comment]
Hi,

Can you please tell me what accuracy/mAP values you got modifying the model described here? I am stuck at 84% accuracy (by adding LSTM layers and increasing the frame size) and was wondering if it could be at all possible to improve from here.

**Comment by tuanchien** [comment]
@Falmi You can try: http://albumentations.ai for augmentations

@godatta Joon Son Chung's design got 0.87 in the leaderboard. http://activity-net.org/challenges/2019/evaluation.html
See his original paper for details. I linked it in README.

**Comment by Falmi** [comment]
> Hi,
> 
> Can you please tell me what accuracy/mAP values you got modifying the model described here? I am stuck at 84% accuracy (by adding LSTM layers and increasing the frame size) and was wondering if it could be at all possible to improve from here.

**Comment by Falmi** [comment]
> Hi,
> 
> Can you please tell me what accuracy/mAP values you got modifying the model described here? I am stuck at 84% accuracy (by adding LSTM layers and increasing the frame size) and was wondering if it could be at all possible to improve from here.
